In [5]:
import pandas as pd

url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(url, sep='\t')
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 21.0 KB

In [6]:
new_columns = ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
titanic_df.columns = new_columns
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [8]:
titanic_df['Age'][titanic_df['Age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: Age, dtype: float64

In [10]:
titanic_df['Age'][titanic_df['Age'].isnull()]
titanic_df['Age'].isnull().sum()

np.int64(30)

In [12]:
titanic_df['Age'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: Age, Length: 156, dtype: bool

In [14]:
titanic_df.loc[titanic_df['Age'].notnull(), ['Age', 'Name']]
titanic_df.loc[titanic_df['Age'].isnull(), ['Age', 'Name']]

     Age                                            Name
5    NaN                                Moran, Mr. James
17   NaN                    Williams, Mr. Charles Eugene
19   NaN                         Masselmani, Mrs. Fatima
26   NaN                         Emir, Mr. Farred Chehab
28   NaN                   O'Dwyer, Miss. Ellen "Nellie"
29   NaN                             Todoroff, Mr. Lalio
31   NaN  Spencer, Mrs. William Augustus (Marie Eugenie)
32   NaN                        Glynn, Miss. Mary Agatha
36   NaN                                Mamee, Mr. Hanna
42   NaN                             Kraeff, Mr. Theodor
45   NaN                        Rogers, Mr. William John
46   NaN                               Lennon, Mr. Denis
47   NaN                       O'Driscoll, Miss. Bridget
48   NaN                             Samaan, Mr. Youssef
55   NaN                               Woolner, Mr. Hugh
64   NaN                           Stewart, Mr. Albert A
65   NaN                        Moubarek, Master. Gerios
76   NaN                               Staneff, Mr. Ivan
77   NaN                        Moutal, Mr. Rahamin Haim
82   NaN                  McDermott, Miss. Brigdet Delia
87   NaN                   Slocovski, Mr. Selman Francis
95   NaN                     Shorney, Mr. Charles Joseph
101  NaN                Petroff, Mr. Pastcho ("Pentcho")
107  NaN                          Moss, Mr. Albert Johan
109  NaN                             Moran, Miss. Bertha
121  NaN                      Moore, Mr. Leonard Charles
126  NaN                             McMahon, Mr. Martin
128  NaN                               Peter, Miss. Anna
140  NaN                   Boulos, Mrs. Joseph (Sultana)
154  NaN                           Olsen, Mr. Ole Martin

In [15]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('N')
titanic_df['Cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: Cabin, Length: 156, dtype: str

In [19]:
titanic_df['Cabin'].value_counts()

Cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [20]:
titanic_df['Cabin'][0]

'N'

In [21]:
titanic_df['Cabin']=titanic_df['Cabin'].apply(lambda x: x[0])
titanic_df['Cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: Cabin, Length: 156, dtype: str

In [22]:
titanic_df_copy=titanic_df.copy()
titanic_df_copy

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [24]:
titanic_df_copy['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [25]:
titanic_df_copy['Age']=titanic_df_copy['Age'].fillna(titanic_df_copy['Age'].mean())
titanic_df_copy['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: Age, Length: 156, dtype: float64

In [26]:
copy_titanic_df=titanic_df.copy()
copy_titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [27]:
hex(id(titanic_df))
hex(id(copy_titanic_df))

'0x1cab5f9d9b0'

In [28]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [29]:
copy_titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [30]:
copy_titanic_df['Age']=0
copy_titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [31]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S